services:
    rpi-imagegen:
        platform: linux/arm64
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-imagegen:latest
        volumes:
            - ./output:/home/imagegen/rpi-image-gen/output